= Push-Button Library for Arduino =

This library allows you to control a pushbutton or any mechanical key. For each instantiated object it is possible to control only one key. The "button_loop" method must be placed in the loop function or in a timer to run constantly. The "pressed" method indicates that the button has been pressed. The blessing of this library is to eliminate the bouncing effect of mechanical switches.

For more information about this library please visit us at
https://github.com/canalBrincandoComIdeias/PushButton.git

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
